### ISSUE TITLE
Push notifications disappear if app is opened

### ISSUE THREAD

**Issue by christopheblin** [OneSignal/OneSignal-iOS-SDK#406]
**Description:**

If my app is opened and a notification is received, the app is briefly displayed on the top of the screen => OK
Now, if I open the iOS notification panel by dragging the top of the screen to the bottom, I can see the notification but it immediately disappear.

From what I've seen, this may be due to https://documentation.onesignal.com/v5.0/docs/troubleshooting-ios#section-previous-push-notifications-disappear
=> this is not the case, the notification is sent with "Badges | Increment by 1" (notif id = 43cc6863-4def-438d-9296-ee284c1b39c4) and I also tried using this flag

The closest issue I find about this here is https://github.com/OneSignal/OneSignal-iOS-SDK/issues/338, however this does not occur (i.e I correctly receive push when app is closed and app correctly opens when notif is clicked)

**Environment**
iOS SDK installed with pod 'OneSignal', '>= 2.6.2', '< 3.0'

**Steps to Reproduce Issue:**
1. Open the app
2. Send a push from our server to one signal
3. Notif is received and small popup is displayed
4. Opening notif history => notif immediately disappear

**Comment by Nightsd01** [comment]
@christopheblin does this occur for you for all notifications, even where you *dont* set any badge count related fields?

**Comment by Nightsd01** [comment]
@christopheblin also, are you opening the app at any point before pulling down Notification Center?

**Comment by christopheblin** [comment]
@Nightsd01 

does this occur for you for all notifications, even where you dont set any badge count related fields?
-> No, if I do not set the ios_badgeCount / ios_badgeType, the notification stays opened if the app is opened and disappears only when the user clicks on it or dismisses it (this is what I want, but I also want the bdge on the app if the app is closed).

are you opening the app at any point before pulling down Notification Center?
-> Yes, the problem occurs ONLY if the app is opened

**Comment by christopheblin** [comment]
OK I got it working, I was misled by the doc saying "OneSignal_disable_badge_clearing = false in your application's Info.plist." at https://documentation.onesignal.com/v5.0/docs/troubleshooting-ios#section-previous-push-notifications-disappear

Indeed, you must set this flag to **true** (instead of false) -> OneSignal does not clear the badge automatically anymore when the flag is true.

This is done at https://github.com/OneSignal/OneSignal-iOS-SDK/blob/8242f97fd68c558251e981f4d6b2dd490728f477/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L1761

The counterpart, of course, is that you have to do decrement/clear the badge count manually because the operating system does not automatically decrement the badge count when you open the app !

All that said, the only thing that really works for badges (be it for iOS or Android) is that the server must send the number of unread notifications to display.
Doing that, you also support multi-devices correctly.

**Comment by Nightsd01** [comment]
Thanks for noticing that, we've fixed our doc

**Comment by lethianqt94** [comment]
It still happens. https://documentation.onesignal.com/docs/troubleshooting-ios#section-previous-push-notifications-disappear. This solution is not working.

**Comment by twboc** [comment]
By default foreground notifications are not displayed. If you want OneSignal to force display the notification you need to add a listener to foreground events and then call the display method.

You need [SDK version 4](https://github.com/OneSignal/react-native-onesignal/issues/1079) to do this.

I attached react-native typescript example below:

```
   OneSignal.Notifications.addEventListener('foregroundWillDisplay',
       (event: NotificationWillDisplayEvent) => {
          event.notification.display()
       })
```

**Comment by DanielStormOutside** [comment]
Add this to your `plist` so the SDK does not automatically clear notifications from the Notification Center: https://documentation.onesignal.com/docs/en/badges#ios-badges

```
<key>OneSignal_disable_badge_clearing</key>
<true/>
```
