### ISSUE TITLE
Invalid bitcode version (Producer: '800.0.24.1_0' Reader: '703.0.31_0')

### ISSUE THREAD

**Issue by PAHANIUS** [OneSignal/OneSignal-iOS-SDK#51]
I found that new version of SDK compiled by new XCode 8.
And if you are use XCode 7 with 2.0.3 build of SDK you get "Invalid bitcode version" error
But with 1.13.3 everything is ok!

Waiting for solving this problem.

**Comment by JKalash** [comment]
Hi,

The following error was resolved with OneSignal SDK 2.0.5.

Thank You.

**Comment by hassanmah** [comment]
Hi,

This is still happening,

I am installing OneSignal via cocoa pods using 

> pod 'OneSignal'

And it keeps downloading 2.0.3.

Thanks

**Comment by hjanuschka** [comment]
@JKalash  this is still an issue.
using xcode 7.3 to compile throws invalid bitcode version.

```
pod 'OneSignal', '=2.1.5'
```

fixes it - can you have a look at it? - and include xcode7 bitcode too?

**Comment by adambolcsfoldi** [comment]
This is happening again with version 2.1.11 (and possibly earlier 2.1 versions).  Is this intentional, i.e. are you not supporting XCode 7 from now on?

**Comment by speedy99** [comment]
This means you have a pod that was compiled with Xcode 8, and you are running/linking with Xcode 7. I had the same issue with a different pod. You have two choices, set enable bit code = NO in your project, or upgrade your dev environment to Xcode 8.
