### ISSUE TITLE
Egypt blocking OneSignal - Can't subscribe user to Onesignal push notification always returns null Help wanted!!

### ISSUE THREAD

**Issue by shadyelkassas7** [OneSignal/OneSignal-iOS-SDK#554]
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        FirebaseApp.configure()
          OneSignal.add(self as OSSubscriptionObserver)
        
        
        let notificationReceivedBlock: OSHandleNotificationReceivedBlock = { notification in

             print("Received Notification: \(notification!.payload.notificationID)")
          }

          let notificationOpenedBlock: OSHandleNotificationActionBlock = { result in
             // This block gets called when the user reacts to a notification received
             let payload: OSNotificationPayload = result!.notification.payload

             var fullMessage = payload.body
             print("Message = \(fullMessage)")

             if payload.additionalData != nil {
                if payload.title != nil {
                   let messageTitle = payload.title
                      print("Message Title = \(messageTitle!)")
                }

                let additionalData = payload.additionalData
                if additionalData?["actionSelected"] != nil {
                   fullMessage = fullMessage! + "\nPressed ButtonID: \(additionalData!["actionSelected"])"
                }
             }
          }

          let onesignalInitSettings = [kOSSettingsKeyAutoPrompt: false,
             kOSSettingsKeyInAppLaunchURL: true]

          OneSignal.initWithLaunchOptions(launchOptions,
             appId: "Removed app id",
             handleNotificationReceived: notificationReceivedBlock,
             handleNotificationAction: notificationOpenedBlock,
             settings: onesignalInitSettings)

          OneSignal.inFocusDisplayType = OSNotificationDisplayType.notification

        
        
        
     
      OneSignal.promptForPushNotifications(userResponse: { accepted in
        if(accepted){
            OneSignal.setSubscription(true)
        }else{
           
        }
      })
        
       
        
        return true
        
    
    }

This is my observer which fires as soon as the app runs even before i allow notifications giving me null push notification

    func onOSSubscriptionChanged(_ stateChanges: OSSubscriptionStateChanges!) {
        if !stateChanges.from.subscribed && stateChanges.to.subscribed {
           print("Subscribed for OneSignal push notifications!")
        }
        print("SubscriptionStateChange: \n\(stateChanges)")

        //The player id is inside stateChanges. But be careful, this value can be nil if the user has not granted you permission to send notifications.
        if let playerId = stateChanges.to.userId {
           print("Current playerId \(playerId)")
        }
     }

it also gives this error 

SubscriptionStateChange: 
Optional(<OSSubscriptionStateChanges:
from: <OSSubscriptionState: userId: (null), pushToken: (null), userSubscriptionSetting: 1, subscribed: 0>,
to:   <OSSubscriptionState: userId: (null), pushToken: 8924c708393c86a36ec29b4d0aa01d265c40a911258f1395997859f4c6687b21, userSubscriptionSetting: 1, subscribed: 0>

**Comment by shadyelkassas7** [comment]
SDK version >=2.6.2  & <3.0

**Comment by smsmdida** [comment]
Samething using RN wrapper on ios 13.1.2
but working fine on 13.0

**Comment by shadyelkassas7** [comment]
Can you tell me what should i do to make it work?

**Comment by IbraD00** [comment]
Humm, i have same problem when user using proxy or ad blocker ... userId was nil

**Comment by shadyelkassas7** [comment]
I’m not using both of those things

**Comment by rgomezp** [comment]
Couple questions:
1. Are you in Egypt?
2. This is actually expected behavior (it should subscribe after about 30 seconds, just not immediately)

**Comment by shadyelkassas** [comment]
Yes I am in Egypt I found that onesignal.com is blocked but app.onesignal.com isn't, so is there a way to send the http request to app.onesignal.com instead of onesignal.com?

**Comment by rgomezp** [comment]
Unfortunately not

**Comment by shadyelkassas7** [comment]
Then how can I solve this problem?

**Comment by rgomezp** [comment]
You will need to reach out to your ISP and request that they unblock OneSignal

**Comment by DanielRaouf** [comment]
@rgomezp I am in Egypt. It works on Android but not on ios so how is that happening ?

**Comment by gdeglin** [comment]
Hi all. If you are still experiencing this, please let us know who your ISP is. We are working on resolving the issue and we believe it has been at least partially fixed.

**Comment by abdallaemadeldin** [comment]
@gdeglin ISP is WE.

**Comment by rgomezp** [comment]
Orange, Vodafone and WE customers should be working

**Comment by gdeglin** [comment]
@abdallaemadeldin We received news today that it should be fixed on WE.

Could you confirm if it is fixed or share more details about what you are experiencing? If you still have the problem, please also try clearing your DNS cache (You can google for instructions on how to do this), and try again. Thank you.

**Comment by shadyelkassas** [comment]
i tried opening it from several devices and cleared the dns cache and it's still not working

**Comment by DanielRaouf** [comment]
@gdeglin I tried using WE and Orange and still is not working.

**Comment by gdeglin** [comment]
Thank you for the information! We're continuing to work on resolving this based on your feedback. We've heard from several folks that the problem is resolved with most ISPs, but it seems like it is still affecting some users.

It's possible it will start working again on its own (Please let us know if the problem goes away), but we're doing what we can in case there's additional work that needs to be done.

**Comment by zanohikaru7** [comment]
@gdeglin I'm here in Philippines, it's always return null in every ISP here. I tried Smart, Globe, Converge.

**Comment by AmrAlmagic** [comment]
any update to solve these issues?

**Comment by HebaMohamed** [comment]
Hello @gdeglin thanks for your efforts team but unfortunately we still have that problem in egypt, as tested with We, Etisalat, Vodafone, all not woking

There is update to that issue please? Egypt's customers are highly affected

**Comment by abdallaemadeldin** [comment]
@HebaMohamed  @AmrAlmagic @DanielRaouf  i use app center till they found solution

**Comment by DanielRaouf** [comment]
@abdallaemadeldin I am using vpns in my dev environment to avoid the blocking. Sometimes I use also browserstack to test a compiled version.

**Comment by AmrAlmagic** [comment]
@abdallaemadeldin  How can I use it?
I use [OneSignal Cordova SDK](https://github.com/OneSignal/OneSignal-Cordova-SDK)

**Comment by abdallaemadeldin** [comment]
@AmrAlmagic 
here is cordova doc: https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/cordova

**Comment by AmrAlmagic** [comment]
@abdallaemadeldin 
I already use it and worked fine until 3 months before but recently I get the same issues her and an I mentioned for it before issues #586
I can't find an alternative solution for it with Ionic until now.
also, I tried use firebase push notification but not receive any message for ios

**Comment by AmrAlmagic** [comment]
@abdallaemadeldin 
thanks, I will try it and come back to you.

**Comment by jkasten2** [comment]
The change to `use api.onesignal.com` is now included in the release 2.13.0

https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.13.0
