### ISSUE TITLE
Demo project on SDK 2.1.0 will not build

### ISSUE THREAD

**Issue by DeanmvSG** [OneSignal/OneSignal-iOS-SDK#69]
**Steps to reproduce:**

Download the Objective C 2.1.0 release from [here](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.1.0) and load project in Xcode 

Load up project in Xcode and when trying to build you get  
```
Type specifier missing, defaults to 'int'
```
```
Expected '}'
```
and
```
Incompatible block pointer types sending 'int ((^)(void))' to parameter of type 'OSHandleNotificationActionBlock' (aka 'void (^)(OSNotificationOpenedResult *__strong)')
```
Which then causes a knock on effect of 
```
Use of undeclared identifier 'result'
```

Swift project builds perfectly.

**Software**
* macOS 10.12 Beta 8
* Xcode 7.3.1
* One Signal SDK 2.1.0

**Comment by JKalash** [comment]
Fixed w/ [2.1.1](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.1.1)

**Comment by simplyi** [comment]
I have just added Onesignal into my project using cocoa pods and the error is still there. 
tried specifying version 2.1.1 in pod file but that did not help...

pod 'OneSignal','2.1.1'

How can I fix it?
