### ISSUE TITLE
Error when importing via Swift Package Manager

### ISSUE THREAD

**Issue by rivertiger** [OneSignal/OneSignal-iOS-SDK#713]
**Description:**

When importing via Swift Package Manager with version specified as exactly 2.14.3, XCode 11.6 prompts an import error saying "no Package.swift manifest for version 2.14.3.

**Environment**

**Steps to Reproduce Issue:**

1. import OneSignal github link into XCode Swift Package Manager.
2. Enter exact version of 2.14.3.  Error shown (see image below).

**Anything else:**

![image](https://user-images.githubusercontent.com/120056/88753235-92280680-d110-11ea-9630-b615d5ad7a93.png)

**Comment by ksloginov** [comment]
The reason is that SPM support has been implemented in master, but hasn't released just yet.

You can import from branch "master" instead of importing by version code

**Comment by gpape** [comment]
Importing from `master` errors on the symbols `OS_INFLUENCE_CHANNEL_TO_STRINGS` and `OS_INFLUENCE_CHANNEL_FROM_STRINGS`, which are used but don't appear to be defined.

**Comment by rgomezp** [comment]
Howdy,
This should be resolved now that we have made the official release. Cheers

**Comment by Krivoblotsky** [comment]
Still see this issue in 2.15.0. 
`OS_INFLUENCE_CHANNEL_FROM_STRINGS ` is not imported.

**Comment by makoni** [comment]
Same issue with OS_INFLUENCE_CHANNEL_FROM_STRINGS with release

**Comment by Krivoblotsky** [comment]
I've fixed it in my fork, not sure the fix is appropriate, but the reason is forgotten outdated file. 
https://github.com/Krivoblotsky/OneSignal-iOS-SDK/commit/c56928b6c174dfd81c3bbbf344e40ae57890287b

**Comment by rgomezp** [comment]
Hello,
We released a new version with a fix. Thank you for bringing this up.

**Comment by emawby** [comment]
This was caused by an unused file hanging around in the Source directory. It is fixed in 2.15.1
