### ISSUE TITLE
NSInvalidUnarchiveOperationException Crash on 2.12.0. Even after updating to 2.14.1.

### ISSUE THREAD

**Issue by musmanjaved** [OneSignal/OneSignal-iOS-SDK#739]
**Description:**
Recently we released our App with OneSignal 2.12.0 and got crash reports from live user. We updated OneSignal to 2.14.1 considering the issue has been fixed in [Release 2.14.1](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.14.1).
But we still got crash reports in 2.14.1. Issue is not fixed.

**Environment**

1. 2.14.1
1. cocoapods

**Steps to Reproduce Issue:**

1. This crash is not reproduced locally on development side
1. Crash is reported by live users on Crashlytics

**Anything else:**

Fatal Exception: NSInvalidUnarchiveOperationException
0  CoreFoundation                 0x1be3f9344 __exceptionPreprocess
1  libobjc.A.dylib                0x1be10ecc0 objc_exception_throw
2  Foundation                     0x1be7584d8 -[NSCoder(Exceptions) __failWithExceptionName:errorCode:format:]
3  Foundation                     0x1be7585ec -[NSCoder(Exceptions) __failWithExceptionName:errorCode:format:]
4  Foundation                     0x1be7c6f20 _decodeObjectBinary
5  Foundation                     0x1be715f40 -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:]
6  Foundation                     0x1be6e8c94 -[NSArray(NSArray) initWithCoder:]
7  Foundation                     0x1be7c75a8 _decodeObjectBinary
8  Foundation                     0x1be7c6a48 _decodeObject
9  Foundation                     0x1be6cf07c -[NSKeyedUnarchiver decodeObjectForKey:]
10 Foundation                     0x1be724ad0 +[NSKeyedUnarchiver unarchiveObjectWithData:]
11 MyApp                          0x1051da9bc -[OneSignalUserDefaults getSavedCodeableData:defaultValue:] + 136 (OneSignalUserDefaults.m:136)
12 MyApp                          0x1051cd650 +[OSOutcomesUtils getCachedReceivedNotifications] + 141 (OSOutcomesUtils.m:141)
13 MyApp                          0x1051e2e70 -[OneSignalSessionManager getIndirectNotificationIds] + 207 (OneSignalSessionManager.m:207)
14 MyApp                          0x1051e2420 -[OneSignalSessionManager restartSessionIfNeeded] + 64 (OneSignalSessionManager.m:64)
15 MyApp                          0x1051ab68c +[OneSignal registerUserInternal] + 1497 (OneSignal.m:1497)
16 libdispatch.dylib              0x1be09a134 _dispatch_call_block_and_release
17 libdispatch.dylib              0x1be09b5ac _dispatch_client_callout
18 libdispatch.dylib              0x1be0a1a64 _dispatch_lane_serial_drain
19 libdispatch.dylib              0x1be0a2498 _dispatch_lane_invoke
20 libdispatch.dylib              0x1be0aba5c _dispatch_workloop_worker_thread
21 libsystem_pthread.dylib        0x1be101718 _pthread_wqthread
22 libsystem_pthread.dylib        0x1be1079c8 start_wqthread

**Comment by emawby** [comment]
Hello, unfortunately not all cases that caused this crash were fixed in 2.14.1. [Additional fixes were needed](https://github.com/OneSignal/OneSignal-iOS-SDK/commit/7e4048956d911ffed3db98bac42610ccfcc2aed4) that were released in version 2.15.2

**Comment by rgomezp** [comment]
Howdy @musmanjaved ,
Can you please test with the latest version? Cheers

**Comment by AhrenFullStop** [comment]
I have tested with 2.15.2 and still getting crashes. I am having similar but persistent issue with the app on IOS claiming to be on line 194 of OneSignalPush.m. I'm creating an Ionic 4 app with push notification capability. This seems to work perfectly on older IOS devices, but newer ones (IOS 14+) seem to crash.

https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/22660bd5e48cc38c13b2e4268fa42d048ebbb94b/src/ios/OneSignalPush.m#L194

The last 10 items on the crash backtrace are:
```
Last Exception Backtrace:
0   CoreFoundation                	0x1af14a5ac __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1c323842c objc_exception_throw + 60 (objc-exception.mm:565)
2   CoreFoundation                	0x1af054a2c -[NSObject(NSObject) doesNotRecognizeSelector:] + 144 (NSObject.m:146)
3   CoreFoundation                	0x1af14d130 ___forwarding___ + 1444 (NSForwarding.m:3597)
4   CoreFoundation                	0x1af14f420 _CF_forwarding_prep_0 + 96
5   School Bozza                  	0x1042d7620 -[OneSignalPush init:] + 676 (OneSignalPush.m:194)
6   School Bozza                  	0x10432c68c 0x1042bc000 + 460428
7   School Bozza                  	0x1042c7a90 -[CDVWKWebViewEngine handleCordovaMessage:] + 180 (CDVWKWebViewEngine.m:616)
8   School Bozza                  	0x1042c794c -[CDVWKWebViewEngine userContentController:didReceiveScriptMessage:] + 124 (CDVWKWebViewEngine.m:602)
9   School Bozza                  	0x1042c8c14 -[CDVWKWeakScriptMessageHandler userContentController:didReceiveScriptMessage:] + 100 (CDVWKWebViewEngine.m:822)
10  WebKit                        	0x1bb3bd4c4 ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&) + 232 (WKUserContentController.mm:148)
```
Line 5 gives us what I think is the culprit.

Things I've already tried:
- Older version of the Podfile
- Remove and add back ios platform
- Remove and add cordova plugin
- Different versions of cordova plugin
- Adding in a 'setTimeout' to delay the initialization somewhat
- my current Pod version is 2.15.2

Nothing seems to work. I am initializing in my app.component.ts within the platform. ready function like this:

```
initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
      setTimeout(() => {
        this.oneSignalInit();
        this.uId.get().then((uuid: any) => {});
      }, 1000);
    });
  }
```

And then I'm running the init like this:
```
oneSignalInit() {
    try {
      // set onesignal id
      const oldId = localStorage.getItem('onesignal_id');
      if (oldId && oldId.length > 0) {
        console.log('We have already registered with one signal');
      } else {
        if (this.platform.is('ios')) {
          this.oneSignal.addTrigger("prompt_ios", "true");
          this.oneSignal.startInit(environment.ONESIGNAL_APP_ID, '');
        } else {
          this.oneSignal.startInit(environment.ONESIGNAL_APP_ID, environment.FIREBASE_SENDERID);
        }
        // notification configuration
        this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.Notification); 
        this.oneSignal.setSubscription(true);
        this.oneSignal.enableVibrate(true);
        this.oneSignal.enableSound(true);
        try {
          // get unique id from onesignal and register with device
          this.oneSignal.getIds().then((usersIds: any) => {
            console.log('Registered with onesignal');
            localStorage.setItem('onesignal_id', usersIds.userId);
          }).catch((err: any) => {
            console.log(err, 'one');
          });
        } catch (e) {
          console.log(e);
        }
      }
      this.oneSignal.endInit();
    } catch (e) {
      console.log(e, 'try');
      this.oneSignal.endInit();
    }
  }
```

Please if anyone can be of assistance, it would be amazing, I can't even imagine what the issue could be, others don't seem to face the same issue, so it must be something stupid that I'm doing.

**Comment by AhrenFullStop** [comment]
Okay so I found the issue, so in my app initialization i used:

```this.oneSignal.startInit(environment.ONESIGNAL_APP_ID, ' ');```

But the issue was actually a null string, meaning that the app was not successfully importing that variable. I fixed that by simply hardcoding the App ID in the actual OneSignalPush.m file... It's not good practice but it stops the app from crashing.

**Comment by emawby** [comment]
Closing as fixed
