### ISSUE TITLE
Firebase Phone Auth - OneSignal Compatibility Conflict

### ISSUE THREAD

**Issue by rgomezp** [OneSignal/OneSignal-iOS-SDK#790]
### **Description:**

To summarize, it looks like there is a conflict between OneSignal & Firebase phone auth due to Firebase swizzling in a way that is incompatible with OneSignal. It's likely due to Google's swizzling code based on the behavior described in the reports, however we will consider providing a way to disable swizzling in the future.

Reported in:

* [Flutter](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/245)
* [React Native](https://github.com/OneSignal/react-native-onesignal/issues/1080)

### Environment
**Report 1 (Flutter)**
macOS 10.15.4
Flutter 1.17.1
Flutter packages:
onesignal_flutter 2.4.1
firebase 7.2.1
firebase_auth 0.15.5+3
Xcode 11.4.1
Pods:
OneSignal 2.13.1
Firebase/Core 6.21.0
Firebase/Auth 6.21.0
iPhone 11 Pro running iOS 13.4.1

**Report 2 (RN)**
"@react-native-firebase/app": "^8.4.6",
"@react-native-firebase/auth": "^9.3.1"
info Fetching system and libraries information...
(node:76962) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 3.00 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_221 - /usr/bin/javac
    Python: 3.8.5 - /usr/local/opt/python/libexec/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    _react-native_: Not Found**Steps to Reproduce Issue:**

**Steps to Reproduce Issue:**
See above linked reports.

**Note:** this is reproducible in the new major release as well

**Anything else:**

## Next Steps
We will need to have a project with the minimal amount variables to narrow things down. A barebones example project reproducing the issue. Ideality a native Swift or Objective-c project but this may also be specific to Flutter or React Native. Once this is available with will greatly help Google or OneSignal pinpoint the issue if reproducible.

We don't have an **ETA** so we do appreciate everyone's patience while we resolve.

**Comment by emawby** [comment]
If possible disabling swizzling in the Firebase sdk might resolve this issue. See instructions [here](https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling)

**Comment by jkasten2** [comment]
The issue was related to a Swizzling forwarding issue not happening if a notification was received while the app is in the foreground. This is now resolved in the following version:
https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.2.0

**Comment by abdelrahmanbonna** [comment]
@jkasten2 is negative; the issue is still happening in the latest release.

**Comment by jkasten2** [comment]
@abdelrahmanbonna Thanks for reporting. A lot has changed since this issue was created, can you try newest OneSignal and Firebase versions? If you can still reproduce can you open a new issue with environment details like the original post?

**Comment by abdelrahmanbonna** [comment]
@jkasten2  ok, I am using the latest OneSignal SDK and Flutter package but not the latest Firebase packages so I will try updating Firebase.
