### ISSUE TITLE
iOS 10 application:didReceiveRemoteNotification:fetchCompletionHandler:  not called for silent notifications in background

### ISSUE THREAD

**Issue by dcdspace** [OneSignal/OneSignal-iOS-SDK#85]
Upon updating my app to iOS 10 and installing the latest OneSignal SDKs, I can no longer perform background functionality on a silent push with the content-enabled flag. The callbacks are still triggered for non-silent notifications, however I cannot act upon notifications in the background now.

Any advice is appreciated

**Comment by JKalash** [comment]
Hi there,

Thank you for the feedback. Was able to reproduce the bug. Will be releasing an update to the SDK fixing the issue within the next 24 hours.

**Comment by dcdspace** [comment]
Hi @JKalash
Thanks for taking a look at the issue. 

I was able to solve it simply by restarting my device and it has worked smoothly since then, so I'm curious as to if there was an actual problem still. 

Thanks

**Comment by Gorhom** [comment]
Thanks @dcdspace for the tip. it worked for the current build on the device, but when i deploy another build, it didn't work any more !

current issues :
- Custom notification sound not working
- handleNotificationReceived not triggered

Thanks

**Comment by JKalash** [comment]
Fixed as of [2.1.11](https://github.com/OneSignal/OneSignal-iOS-SDK/commit/2c0202648f9f1b1e42e7d8e17fbd3c0314f830e0)

**Comment by Gorhom** [comment]
thanks @JKalash ! now "handleNotificationReceived" working fine ! but custom notification sound still not working .. it works only when you restart the device !

**Comment by AlbertoGuerreroMartin** [comment]
I'm sending notifications with 'Content available' option checked, but when my application is **not running** (not event in background), it never wakes and `application:didReceiveRemoteNotification:fetchCompletionHandler:` is never called. I've tried almost everything, but nothing works. I'm testing under iOS 10.0.2.

I'm not really sure if it's a bug, or a mistake in my implementation, but I'd appreciate any help on this, cause I'm starting to get a little desperation 😅 
Thanks in advance!

**Comment by jkasten2** [comment]
@AlbertoGuerreroMartin See the 3 points under the OneSignal troubleshooting [iOS notifications with action buttons or media set not displaying](https://documentation.onesignal.com/docs/troubleshooting-ios#section-ios-notifications-with-action-buttons-or-media-set-not-displaying) section as these features also reply on content-available.

**Comment by CalvinTp** [comment]
@AlbertoGuerreroMartin did you manage to fix this? I am facing the same issue as the didReceiveRemoteNotification:fetchCompletionHandler is never called. 

@jkasten2 I have looked into the troubleshooting, and it does not help. 

Any advice anyone?
